### ISSUE TITLE
Метод НайтиПоПути() не работает, если база создана через vrunner@1.9.0

### ISSUE THREAD

**Issue by ovcharenko-di** [ret-Phoenix/parserV8i#12]
Воспроизведение:

- в выбранном каталоге запустить `vrunner init-dev`
- открыть список баз, убедиться, что зарегистрирована новая база
- открыть информационную базу, убедиться, что она корректно запускается
- вызвать `Парсер.НайтиПоПути(<ПутьКНовойБазе>)`
- убедиться, что библиотека ее не находит

Причина:
vrunner регистрирует базу в файле ibases.v8i без точки запятой на конце. Это не приводит к ошибке при запуске 1C, однако мешает ParserV8i найти базу по ее пути.

Источник ошибки на стороне ParserV8i:
https://github.com/ret-Phoenix/parserV8i/blob/934e315601a71bd856df59062367249989b2c1fa/src/parserV8i.os#L214

В указанной строке проверяется, что в регулярном выражении 5 групп. Когда есть точка с запятой, их действительно пять. Но когда точки с запятой нет, то регулярное выражение определяет 3 группы и не заходит в условие.

**Comment by artbear** [comment]
@ovcharenko-di еще бы в ванесса-раннер исправить, лучше делать совместимо с 1С )
