### ISSUE TITLE
Вернуть обратно исполняемый скрипт для удаления кеша базы

### ISSUE THREAD

**Issue by artbear** [ret-Phoenix/parserV8i#3]
Также его нужно документировать.

>скрипт очистки кеша баз, 
если передать `clearCash all` - пройдется по всем базам в файле путей и грохнет кеш, 
а можно почистить только для конкретной базы - тогда путь указать P <путь к базе>

**Comment by ret-Phoenix** [comment]
я убрал работу с командной строкой.
теперь реализуется в виде ООП:

Парсер = Новый ПарсерСпискаБаз;
Парсер.УстановитьФайл();

Чистильщик = Новый ОчисткаКеша();
Чистильщик.УстановитьПарсер(Парсер);

// Очистить весь кеш
Чистильщик.ОчиститьВесьКеш();

**Comment by artbear** [comment]
Тогда мы потеряли полезный скрипт по очистке кеша :(

**Comment by ret-Phoenix** [comment]
parserV8i/examples/clean-cash.os
